### ISSUE TITLE
大佬Delta社用的什么解包工具

### ISSUE THREAD

**Issue by FFreQD** [jyxjyx1234/misc_game-chs#1]
文本解包需要自己写吗

**Comment by jyxjyx1234** [comment]
目前看到的有两种引擎，一种直接在SD文件里。我现在水平不够没研究透，只能暴力提取文本和替换，文本长度和行数不能变（用了\x00分行）
另一种文本在md_scr.med里，我参考网上的资料写了个解封包、解密、文本提取替换的代码，可以先参考一下。现在代码基本没啥注释，我哪天理一下写个文档啥的吧。
https://github.com/jyxjyx1234/misc_game-chs/blob/main/%E9%AD%94%E6%B3%95%E3%81%AE%E5%AE%88%E8%AD%B7%E5%A7%AB%E3%82%A2%E3%83%AB%E3%83%86%E3%83%9F%E3%83%8A/Lib.py

**Comment by jyxjyx1234** [comment]
前一种每部作品sd文件的格式都会有微妙的变化，得自己看着改，而且人名全部用的N1、N2这种，得去游戏里一个个对。
后一种文本长度可变，挺好弄的。但是人名、文本、资源文件什么的怎么判断我没找出来，只能自己定规则判断。我这里用的正则匹配资源文件代码，然后以引号、括号开头的文本认为是对话，往前找人名，初步生成一个人名列表，手动从中排除一看就不是人名的，然后再根据人名列表进行分类。（在 DXLibScrFile._classify_str方法里）
而且这个是加密的，用的循环加密，需要手动找key。_VIEW文件前几个字节的原文是固定的，通过对比可以找到循环加密的key。（已经在代码中集成，key输入[0]可以输出用那几个字节找出的密钥，肉眼观察找循环节就是key）

**Comment by FFreQD** [comment]
没学过相关知识，不会动手，只能用现成的解/封包工具
